var ENV = {};
(function () {
  "use strict";

  //ENV.GOOGLE_CLIENT_ID = "${GOOGLE_CLIENT_ID}";
  //ENV.GOOGLE_REDIRECT_URI;

  ENV.BASE_API_URL;

  ENV.GITHUB_CLIENT_ID;
  ENV.GITHUB_REDIRECT_URI;
})();
